# Generated by Django 3.1.5 on 2021-01-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('pokemon_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('specialAttack', models.IntegerField(default=0)),
                ('specialDefense', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('evolutions', models.ManyToManyField(related_name='pokemon_pokemon_related', to='pokemon.Pokemon')),
                ('preEvolution', models.ManyToManyField(to='pokemon.Pokemon')),
            ],
        ),
    ]
